#!/bin/bash
# Brain-dead guided setup for release secrets. Walks you through getting both
# the npm token and the VS Code Marketplace PAT, with hand-held instructions
# and direct URLs. Tokens are read with hidden input — they don't show on
# screen and don't end up in shell history.
#
# Run once: bash ./setup-secrets.sh
# Future releases: bash ./release.sh

set -e

SECRETS_FILE="$HOME/.notify-mcp-secrets"

# Try to open URLs in the browser automatically (cross-platform).
open_url() {
  local url="$1"
  if command -v start >/dev/null 2>&1; then
    start "" "$url" 2>/dev/null || true
  elif command -v open >/dev/null 2>&1; then
    open "$url" 2>/dev/null || true
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" 2>/dev/null || true
  fi
}

hr() { echo "--------------------------------------------------------------------------------"; }

clear || true
echo ""
hr
echo "  omni-notify-mcp — one-time release setup"
hr
echo ""
echo "  This walks you through getting two tokens:"
echo "    1. npm token       — for publishing the npm package"
echo "    2. Marketplace PAT — for publishing the VS Code extension"
echo ""
echo "  Both tokens get saved to: $SECRETS_FILE (chmod 600)"
echo "  After this, every release is just: bash ./release.sh"
echo ""
read -rp "  Press Enter to begin..." _

# ── 1. npm token ─────────────────────────────────────────────────────────────
clear || true
echo ""
hr
echo "  STEP 1 of 2 — npm token"
hr
echo ""
echo "  URL (opening in your browser):"
echo "    https://www.npmjs.com/settings/karish911/tokens"
echo ""
echo "  Steps:"
echo "    1. Click 'Generate New Token' (top-right)"
echo "    2. Pick 'Granular Access Token'"
echo "    3. Token name: omni-notify-publish"
echo "    4. Expiration: 90 days (their max)"
echo "    5. Bypass 2FA: ✅ check it (so you don't need an OTP every release)"
echo "    6. Permissions: Read and write"
echo "    7. Packages and scopes: pick 'All packages'"
echo "       (or specifically 'omni-notify-mcp' if you want narrower scope)"
echo "    8. Click 'Generate token' at the bottom"
echo "    9. Copy the token (starts with npm_...) — shown ONLY ONCE"
echo ""
open_url "https://www.npmjs.com/settings/karish911/tokens"
echo ""
read -rsp "  Paste npm token here (input hidden, then Enter): " NPM_TOKEN_INPUT
echo ""
if [ -z "$NPM_TOKEN_INPUT" ]; then
  echo ""
  echo "  ERROR: empty token. Aborting."
  exit 1
fi
case "$NPM_TOKEN_INPUT" in
  npm_*) ;;
  *)
    echo ""
    echo "  WARN: token doesn't start with 'npm_' — that's the usual format."
    echo "        Continuing anyway (maybe npm changed it)."
    ;;
esac
echo "  ✓ npm token captured"

# ── 2. Marketplace PAT ───────────────────────────────────────────────────────
clear || true
echo ""
hr
echo "  STEP 2 of 2 — VS Code Marketplace PAT"
hr
echo ""
echo "  This token publishes the VS Code extension to the marketplace."
echo "  If you've already run 'vsce login MeniHillel' successfully, the"
echo "  credential is cached locally and you can skip this step (just press"
echo "  Enter)."
echo ""
echo "  URL (opening in your browser):"
echo "    https://dev.azure.com/"
echo ""
echo "  Steps:"
echo "    1. Sign in with menihillel@gmail.com (the Microsoft account that"
echo "       owns the MeniHillel marketplace publisher)"
echo "    2. You should land in your Azure DevOps org. If you see"
echo "       'Create new organization', click it and accept defaults."
echo "    3. Top-right corner: click your profile picture/initials"
echo "    4. Click 'Personal access tokens'"
echo "    5. Click '+ New Token'"
echo "    6. Settings:"
echo "       - Name: omni-notify-marketplace"
echo "       - Organization: All accessible organizations  ← critical"
echo "       - Expiration: 1 year (max)"
echo "       - Scopes: Custom defined → expand 'Marketplace' → check 'Manage'"
echo "    7. Click 'Create' → copy the token (shown ONLY ONCE)"
echo ""
open_url "https://dev.azure.com/"
echo ""
read -rsp "  Paste marketplace PAT here (or press Enter to skip): " VSCE_PAT_INPUT
echo ""
if [ -n "$VSCE_PAT_INPUT" ]; then
  echo "  ✓ marketplace PAT captured"
else
  echo "  ⊘ marketplace PAT skipped — vsce login credential will be used"
fi

# ── Write the file ───────────────────────────────────────────────────────────
{
  echo "# Generated by setup-secrets.sh on $(date)"
  echo "# Edit to update tokens, or re-run: bash ./setup-secrets.sh"
  echo ""
  echo "NPM_TOKEN=$NPM_TOKEN_INPUT"
  if [ -n "$VSCE_PAT_INPUT" ]; then
    echo "VSCE_PAT=$VSCE_PAT_INPUT"
  fi
} > "$SECRETS_FILE"

chmod 600 "$SECRETS_FILE"

clear || true
echo ""
hr
echo "  ✓ DONE — wrote $SECRETS_FILE (chmod 600)"
hr
echo ""
echo "  Now ship:  bash ./release.sh"
echo ""
